package BotScript.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6be7L, "BotScript.structure.Area"))) {
        return Collections.<ConceptEditor>singletonList(new Area_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6c0fL, "BotScript.structure.Areas"))) {
        return Collections.<ConceptEditor>singletonList(new Areas_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6c04L, "BotScript.structure.Location"))) {
        return Collections.<ConceptEditor>singletonList(new Location_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731b518L, "BotScript.structure.Script"))) {
        return Collections.<ConceptEditor>singletonList(new Script_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731f413L, "BotScript.structure.StatementList"))) {
        return Collections.<ConceptEditor>singletonList(new StatementList_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
