package BotScript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptArea = new ConceptDescriptorBuilder("BotScript.structure.Area", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6be7L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.lang.core.structure.IType").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L)).childDescriptors(new ConceptDescriptorBuilder.Link(9029359182276226085L, "listOfLocations", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6c04L), false, true, false)).children(new String[]{"listOfLocations"}, new boolean[]{true}).alias("Area", "").create();
  /*package*/ final ConceptDescriptor myConceptAreas = new ConceptDescriptorBuilder("BotScript.structure.Areas", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6c0fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(9029359182276226076L, "listOfAreas", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6be7L), false, true, false)).children(new String[]{"listOfAreas"}, new boolean[]{true}).alias("Areas", "").create();
  /*package*/ final ConceptDescriptor myConceptLocation = new ConceptDescriptorBuilder("BotScript.structure.Location", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x7d4eba5630fc6c04L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.IType").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(9029359182276226099L, "x"), new ConceptDescriptorBuilder.Prop(9029359182276226101L, "y")).properties("x", "y").create();
  /*package*/ final ConceptDescriptor myConceptScript = new ConceptDescriptorBuilder("BotScript.structure.Script", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731b518L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.lang.core.structure.ScopeProvider").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L)).childDescriptors(new ConceptDescriptorBuilder.Link(3085351801494568616L, "statementList", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731f413L), false, false, false)).children(new String[]{"statementList"}, new boolean[]{false}).alias("Script", "").create();
  /*package*/ final ConceptDescriptor myConceptStatement = new ConceptDescriptorBuilder("BotScript.structure.Statement", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731f412L)).interface_().create();
  /*package*/ final ConceptDescriptor myConceptStatementList = new ConceptDescriptorBuilder("BotScript.structure.StatementList", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731f413L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(3085351801494565908L, "statements", MetaIdFactory.conceptId(0x6dab4a3ca32147f8L, 0x863d767666dd7eecL, 0x2ad15f1dd731f412L), true, true, false)).children(new String[]{"statements"}, new boolean[]{true}).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptArea, myConceptAreas, myConceptLocation, myConceptScript, myConceptStatement, myConceptStatementList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0k, conceptFqName)) {
      case 0:
        return myConceptArea;
      case 1:
        return myConceptAreas;
      case 2:
        return myConceptLocation;
      case 3:
        return myConceptScript;
      case 4:
        return myConceptStatement;
      case 5:
        return myConceptStatementList;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0k = new String[]{"BotScript.structure.Area", "BotScript.structure.Areas", "BotScript.structure.Location", "BotScript.structure.Script", "BotScript.structure.Statement", "BotScript.structure.StatementList"};
}
